### ISSUE TITLE
External css path issue

### ISSUE THREAD

**Issue by Harrrrry** [barryvdh/laravel-dompdf#162]
Hello I m new to laravle and dompdf, i follow the instruction but when i adding these line in bootstrap/app.php

 $app->register(\Barryvdh\DomPDF\ServiceProvider::class);
$app->configure('dompdf');

it shows blank page with error in terminal like

[Tue Sep 29 11:16:37 2015] PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class config does not exist' in /var/www/html/innomaid/vendor/laravel/framework/src/Illuminate/Container/Container.php:779
Stack trace:
#0 /var/www/html/innomaid/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): ReflectionClass->__construct('config')
#1 /var/www/html/innomaid/vendor/laravel/framework/src/Illuminate/Container/Container.php(659): Illuminate\Container\Container->build('config', Array)
#2 /var/www/html/innomaid/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(644): Illuminate\Container\Container->make('config', Array)
#3 /var/www/html/innomaid/vendor/laravel/framework/src/Illuminate/Container/Container.php(1234): Illuminate\Foundation\Application->make('config')
#4 /var/www/html/innomaid/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(62): Illuminate\Container\Container->offsetGet('config')
#5 /var/www/html/innomaid/vendor/barryvdh/laravel-dompdf/src/ServiceProvider.php(25): Illuminate in /var/www/html/innomaid/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 779

 and when i comment these, application run perfectly.

One more thing without these line pdf generating if i generate 2 to three line of html but if i use my view page with dynamic data it take more than 15 min. and after that it give errors like
http://stackoverflow.com/questions/32823456/laravel-5-dompdf

please help me i dont know what i am doing wrong

**Comment by Harrrrry** [comment]
Hyy i found that it have some external css path, image path and footer tag issue after removing that it work fine.
How can i use these css file and footer tag ?
